/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 85
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 25
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_Class = 2,
  anon_sym_LBRACK = 3,
  anon_sym_Extension = 4,
  anon_sym_Package = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_COMMA = 8,
  anon_sym_POUNDname = 9,
  anon_sym_COLON = 10,
  anon_sym_SQUOTE = 11,
  anon_sym_POUNDsuperclass = 12,
  anon_sym_POUNDpackage = 13,
  anon_sym_POUNDtag = 14,
  anon_sym_POUNDcategory = 15,
  anon_sym_POUNDinstVars = 16,
  anon_sym_POUNDclassInstVars = 17,
  anon_sym_RBRACK = 18,
  anon_sym_POUND = 19,
  anon_sym_EQ_GT = 20,
  sym_line_continuation = 21,
  sym_dashed_name = 22,
  sym_comment = 23,
  sym_file = 24,
  sym_class_definition = 25,
  sym_method_definition = 26,
  sym_extensions_definition = 27,
  sym_package_definition = 28,
  sym__class_specification = 29,
  sym__class_field = 30,
  sym__simple_name_definition = 31,
  sym__superclass = 32,
  sym__package = 33,
  sym__tag = 34,
  sym__category = 35,
  sym__instance_slots = 36,
  sym__class_slots = 37,
  sym__slots = 38,
  sym_slot_definition = 39,
  aux_sym_extensions_definition_repeat1 = 40,
  aux_sym__class_specification_repeat1 = 41,
  aux_sym__slots_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_Class] = "Class",
  [anon_sym_LBRACK] = "[",
  [anon_sym_Extension] = "Extension",
  [anon_sym_Package] = "Package",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_POUNDname] = "#name",
  [anon_sym_COLON] = ":",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_POUNDsuperclass] = "#superclass",
  [anon_sym_POUNDpackage] = "#package",
  [anon_sym_POUNDtag] = "#tag",
  [anon_sym_POUNDcategory] = "#category",
  [anon_sym_POUNDinstVars] = "#instVars",
  [anon_sym_POUNDclassInstVars] = "#classInstVars",
  [anon_sym_RBRACK] = "]",
  [anon_sym_POUND] = "#",
  [anon_sym_EQ_GT] = "=>",
  [sym_line_continuation] = "line_continuation",
  [sym_dashed_name] = "dashed_name",
  [sym_comment] = "comment",
  [sym_file] = "file",
  [sym_class_definition] = "class_definition",
  [sym_method_definition] = "method_definition",
  [sym_extensions_definition] = "extensions_definition",
  [sym_package_definition] = "package_definition",
  [sym__class_specification] = "_class_specification",
  [sym__class_field] = "_class_field",
  [sym__simple_name_definition] = "_simple_name_definition",
  [sym__superclass] = "_superclass",
  [sym__package] = "_package",
  [sym__tag] = "_tag",
  [sym__category] = "_category",
  [sym__instance_slots] = "_instance_slots",
  [sym__class_slots] = "_class_slots",
  [sym__slots] = "_slots",
  [sym_slot_definition] = "slot_definition",
  [aux_sym_extensions_definition_repeat1] = "extensions_definition_repeat1",
  [aux_sym__class_specification_repeat1] = "_class_specification_repeat1",
  [aux_sym__slots_repeat1] = "_slots_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_Class] = anon_sym_Class,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_Extension] = anon_sym_Extension,
  [anon_sym_Package] = anon_sym_Package,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_POUNDname] = anon_sym_POUNDname,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_POUNDsuperclass] = anon_sym_POUNDsuperclass,
  [anon_sym_POUNDpackage] = anon_sym_POUNDpackage,
  [anon_sym_POUNDtag] = anon_sym_POUNDtag,
  [anon_sym_POUNDcategory] = anon_sym_POUNDcategory,
  [anon_sym_POUNDinstVars] = anon_sym_POUNDinstVars,
  [anon_sym_POUNDclassInstVars] = anon_sym_POUNDclassInstVars,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [sym_line_continuation] = sym_line_continuation,
  [sym_dashed_name] = sym_dashed_name,
  [sym_comment] = sym_comment,
  [sym_file] = sym_file,
  [sym_class_definition] = sym_class_definition,
  [sym_method_definition] = sym_method_definition,
  [sym_extensions_definition] = sym_extensions_definition,
  [sym_package_definition] = sym_package_definition,
  [sym__class_specification] = sym__class_specification,
  [sym__class_field] = sym__class_field,
  [sym__simple_name_definition] = sym__simple_name_definition,
  [sym__superclass] = sym__superclass,
  [sym__package] = sym__package,
  [sym__tag] = sym__tag,
  [sym__category] = sym__category,
  [sym__instance_slots] = sym__instance_slots,
  [sym__class_slots] = sym__class_slots,
  [sym__slots] = sym__slots,
  [sym_slot_definition] = sym_slot_definition,
  [aux_sym_extensions_definition_repeat1] = aux_sym_extensions_definition_repeat1,
  [aux_sym__class_specification_repeat1] = aux_sym__class_specification_repeat1,
  [aux_sym__slots_repeat1] = aux_sym__slots_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Class] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Extension] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Package] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDname] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDsuperclass] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDpackage] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDtag] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDcategory] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDinstVars] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDclassInstVars] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_line_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym_dashed_name] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [sym_class_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_method_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_extensions_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_package_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__class_specification] = {
    .visible = false,
    .named = true,
  },
  [sym__class_field] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_name_definition] = {
    .visible = false,
    .named = true,
  },
  [sym__superclass] = {
    .visible = false,
    .named = true,
  },
  [sym__package] = {
    .visible = false,
    .named = true,
  },
  [sym__tag] = {
    .visible = false,
    .named = true,
  },
  [sym__category] = {
    .visible = false,
    .named = true,
  },
  [sym__instance_slots] = {
    .visible = false,
    .named = true,
  },
  [sym__class_slots] = {
    .visible = false,
    .named = true,
  },
  [sym__slots] = {
    .visible = false,
    .named = true,
  },
  [sym_slot_definition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_extensions_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__class_specification_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__slots_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_category = 1,
  field_class_comment = 2,
  field_class_name = 3,
  field_class_slots = 4,
  field_definition = 5,
  field_name = 6,
  field_package = 7,
  field_slots = 8,
  field_superclass = 9,
  field_tag = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_category] = "category",
  [field_class_comment] = "class_comment",
  [field_class_name] = "class_name",
  [field_class_slots] = "class_slots",
  [field_definition] = "definition",
  [field_name] = "name",
  [field_package] = "package",
  [field_slots] = "slots",
  [field_superclass] = "superclass",
  [field_tag] = "tag",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 7},
  [2] = {.index = 7, .length = 2},
  [3] = {.index = 9, .length = 1},
  [4] = {.index = 10, .length = 1},
  [5] = {.index = 11, .length = 1},
  [6] = {.index = 12, .length = 1},
  [7] = {.index = 13, .length = 1},
  [8] = {.index = 14, .length = 1},
  [9] = {.index = 15, .length = 1},
  [10] = {.index = 16, .length = 1},
  [11] = {.index = 17, .length = 8},
  [12] = {.index = 25, .length = 1},
  [13] = {.index = 26, .length = 2},
  [14] = {.index = 28, .length = 3},
  [15] = {.index = 31, .length = 3},
  [16] = {.index = 34, .length = 14},
  [17] = {.index = 48, .length = 14},
  [18] = {.index = 62, .length = 2},
  [19] = {.index = 64, .length = 5},
  [20] = {.index = 69, .length = 3},
  [21] = {.index = 72, .length = 5},
  [22] = {.index = 77, .length = 5},
  [23] = {.index = 82, .length = 5},
  [24] = {.index = 87, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_category, 1, .inherited = true},
    {field_class_slots, 1, .inherited = true},
    {field_name, 1, .inherited = true},
    {field_package, 1, .inherited = true},
    {field_slots, 1, .inherited = true},
    {field_superclass, 1, .inherited = true},
    {field_tag, 1, .inherited = true},
  [7] =
    {field_class_name, 1},
    {field_name, 1, .inherited = true},
  [9] =
    {field_name, 0, .inherited = true},
  [10] =
    {field_superclass, 0, .inherited = true},
  [11] =
    {field_package, 0, .inherited = true},
  [12] =
    {field_tag, 0, .inherited = true},
  [13] =
    {field_category, 0, .inherited = true},
  [14] =
    {field_slots, 0, .inherited = true},
  [15] =
    {field_class_slots, 0, .inherited = true},
  [16] =
    {field_name, 1},
  [17] =
    {field_category, 2, .inherited = true},
    {field_class_comment, 0},
    {field_class_slots, 2, .inherited = true},
    {field_name, 2, .inherited = true},
    {field_package, 2, .inherited = true},
    {field_slots, 2, .inherited = true},
    {field_superclass, 2, .inherited = true},
    {field_tag, 2, .inherited = true},
  [25] =
    {field_name, 2, .inherited = true},
  [26] =
    {field_name, 1},
    {field_name, 2},
  [28] =
    {field_slots, 0},
    {field_slots, 1},
    {field_slots, 2},
  [31] =
    {field_class_slots, 0},
    {field_class_slots, 1},
    {field_class_slots, 2},
  [34] =
    {field_category, 1, .inherited = true},
    {field_category, 2, .inherited = true},
    {field_class_slots, 1, .inherited = true},
    {field_class_slots, 2, .inherited = true},
    {field_name, 1, .inherited = true},
    {field_name, 2, .inherited = true},
    {field_package, 1, .inherited = true},
    {field_package, 2, .inherited = true},
    {field_slots, 1, .inherited = true},
    {field_slots, 2, .inherited = true},
    {field_superclass, 1, .inherited = true},
    {field_superclass, 2, .inherited = true},
    {field_tag, 1, .inherited = true},
    {field_tag, 2, .inherited = true},
  [48] =
    {field_category, 0, .inherited = true},
    {field_category, 1, .inherited = true},
    {field_class_slots, 0, .inherited = true},
    {field_class_slots, 1, .inherited = true},
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
    {field_package, 0, .inherited = true},
    {field_package, 1, .inherited = true},
    {field_slots, 0, .inherited = true},
    {field_slots, 1, .inherited = true},
    {field_superclass, 0, .inherited = true},
    {field_superclass, 1, .inherited = true},
    {field_tag, 0, .inherited = true},
    {field_tag, 1, .inherited = true},
  [62] =
    {field_definition, 3},
    {field_name, 1},
  [64] =
    {field_name, 0},
    {field_name, 1},
    {field_name, 2},
    {field_name, 3},
    {field_name, 4},
  [69] =
    {field_definition, 4},
    {field_name, 1},
    {field_name, 2},
  [72] =
    {field_superclass, 0},
    {field_superclass, 1},
    {field_superclass, 2},
    {field_superclass, 3},
    {field_superclass, 4},
  [77] =
    {field_package, 0},
    {field_package, 1},
    {field_package, 2},
    {field_package, 3},
    {field_package, 4},
  [82] =
    {field_tag, 0},
    {field_tag, 1},
    {field_tag, 2},
    {field_tag, 3},
    {field_tag, 4},
  [87] =
    {field_category, 0},
    {field_category, 1},
    {field_category, 2},
    {field_category, 3},
    {field_category, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(54);
      ADVANCE_MAP(
        '"', 5,
        '#', 69,
        '\'', 61,
        ',', 58,
        ':', 60,
        '=', 6,
        '[', 55,
        '\\', 2,
        ']', 68,
        '{', 56,
        '}', 57,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xa0 ||
          lookahead == 0x3000 ||
          lookahead == 0xfeff) SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(71);
      END_STATE();
    case 2:
      if (lookahead == '\r') ADVANCE(1);
      if ((!eof && lookahead == 00) ||
          lookahead == '\n') ADVANCE(71);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '#') ADVANCE(69);
      if (lookahead == '\\') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xa0 ||
          lookahead == 0x3000 ||
          lookahead == 0xfeff) SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xa0 ||
          lookahead == 0x3000 ||
          lookahead == 0xfeff) SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(75);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(70);
      END_STATE();
    case 7:
      if (lookahead == 'I') ADVANCE(33);
      END_STATE();
    case 8:
      if (lookahead == 'V') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'V') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(48);
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(46);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(10);
      if (lookahead == 'i') ADVANCE(32);
      if (lookahead == 'n') ADVANCE(11);
      if (lookahead == 'p') ADVANCE(12);
      if (lookahead == 's') ADVANCE(51);
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 26:
      if (lookahead == 'g') ADVANCE(64);
      END_STATE();
    case 27:
      if (lookahead == 'g') ADVANCE(34);
      END_STATE();
    case 28:
      if (lookahead == 'g') ADVANCE(24);
      END_STATE();
    case 29:
      if (lookahead == 'k') ADVANCE(15);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 31:
      if (lookahead == 'm') ADVANCE(22);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 35:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 40:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 41:
      if (lookahead == 's') ADVANCE(66);
      END_STATE();
    case 42:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(67);
      END_STATE();
    case 44:
      if (lookahead == 's') ADVANCE(49);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 47:
      if (lookahead == 's') ADVANCE(50);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 51:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 52:
      if (lookahead == 'y') ADVANCE(65);
      END_STATE();
    case 53:
      if (eof) ADVANCE(54);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '\'') ADVANCE(61);
      if (lookahead == ',') ADVANCE(58);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '}') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xa0 ||
          lookahead == 0x3000 ||
          lookahead == 0xfeff) SKIP(53);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_POUNDname);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_POUNDsuperclass);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_POUNDpackage);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_POUNDtag);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_POUNDcategory);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_POUNDinstVars);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_POUNDclassInstVars);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_line_continuation);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_dashed_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'C') ADVANCE(1);
      if (lookahead == 'E') ADVANCE(2);
      if (lookahead == 'P') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xa0 ||
          lookahead == 0x3000 ||
          lookahead == 0xfeff) SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'x') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'k') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_Class);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'g') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_Package);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_Extension);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 53},
  [2] = {.lex_state = 53},
  [3] = {.lex_state = 53},
  [4] = {.lex_state = 53},
  [5] = {.lex_state = 53},
  [6] = {.lex_state = 53},
  [7] = {.lex_state = 53},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 53},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 53},
  [37] = {.lex_state = 53},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 53},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 53},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 53},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 53},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 53},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 53},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_Class] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_Extension] = ACTIONS(1),
    [anon_sym_Package] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [sym_line_continuation] = ACTIONS(3),
    [sym_dashed_name] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_file] = STATE(77),
    [sym_class_definition] = STATE(79),
    [sym_extensions_definition] = STATE(79),
    [sym_package_definition] = STATE(79),
    [sym_slot_definition] = STATE(79),
    [anon_sym_Class] = ACTIONS(5),
    [anon_sym_Extension] = ACTIONS(7),
    [anon_sym_Package] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(11),
    [sym_line_continuation] = ACTIONS(3),
    [sym_comment] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(15), 1,
      anon_sym_POUNDname,
    ACTIONS(17), 1,
      anon_sym_POUNDsuperclass,
    ACTIONS(19), 1,
      anon_sym_POUNDpackage,
    ACTIONS(21), 1,
      anon_sym_POUNDtag,
    ACTIONS(23), 1,
      anon_sym_POUNDcategory,
    ACTIONS(25), 1,
      anon_sym_POUNDinstVars,
    ACTIONS(27), 1,
      anon_sym_POUNDclassInstVars,
    STATE(8), 1,
      sym__class_field,
    STATE(20), 1,
      sym__simple_name_definition,
    STATE(21), 1,
      sym__superclass,
    STATE(22), 1,
      sym__package,
    STATE(23), 1,
      sym__tag,
    STATE(24), 1,
      sym__category,
    STATE(25), 1,
      sym__instance_slots,
    STATE(26), 1,
      sym__class_slots,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [50] = 16,
    ACTIONS(15), 1,
      anon_sym_POUNDname,
    ACTIONS(17), 1,
      anon_sym_POUNDsuperclass,
    ACTIONS(19), 1,
      anon_sym_POUNDpackage,
    ACTIONS(21), 1,
      anon_sym_POUNDtag,
    ACTIONS(23), 1,
      anon_sym_POUNDcategory,
    ACTIONS(25), 1,
      anon_sym_POUNDinstVars,
    ACTIONS(27), 1,
      anon_sym_POUNDclassInstVars,
    STATE(20), 1,
      sym__simple_name_definition,
    STATE(21), 1,
      sym__superclass,
    STATE(22), 1,
      sym__package,
    STATE(23), 1,
      sym__tag,
    STATE(24), 1,
      sym__category,
    STATE(25), 1,
      sym__instance_slots,
    STATE(26), 1,
      sym__class_slots,
    STATE(35), 1,
      sym__class_field,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [100] = 4,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    STATE(5), 2,
      sym_method_definition,
      aux_sym_extensions_definition_repeat1,
  [115] = 4,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    STATE(6), 2,
      sym_method_definition,
      aux_sym_extensions_definition_repeat1,
  [130] = 4,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    STATE(6), 2,
      sym_method_definition,
      aux_sym_extensions_definition_repeat1,
  [145] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(40), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_identifier,
  [156] = 4,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    ACTIONS(44), 1,
      anon_sym_COMMA,
    STATE(10), 1,
      aux_sym__class_specification_repeat1,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [170] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(46), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [180] = 4,
    ACTIONS(44), 1,
      anon_sym_COMMA,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      aux_sym__class_specification_repeat1,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [194] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(50), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [204] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(52), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [214] = 4,
    ACTIONS(54), 1,
      anon_sym_COMMA,
    ACTIONS(56), 1,
      anon_sym_RBRACK,
    STATE(16), 1,
      aux_sym__slots_repeat1,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [228] = 4,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
    ACTIONS(60), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      aux_sym__class_specification_repeat1,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [242] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(63), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [252] = 4,
    ACTIONS(54), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_RBRACK,
    STATE(17), 1,
      aux_sym__slots_repeat1,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [266] = 4,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    ACTIONS(70), 1,
      anon_sym_RBRACK,
    STATE(17), 1,
      aux_sym__slots_repeat1,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [280] = 3,
    ACTIONS(72), 1,
      anon_sym_LBRACK,
    STATE(34), 1,
      sym__slots,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [291] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(74), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [300] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(76), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [309] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(78), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [318] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [327] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(82), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [336] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(84), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [345] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(86), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [354] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(88), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [363] = 3,
    ACTIONS(90), 1,
      sym_identifier,
    ACTIONS(92), 1,
      anon_sym_POUND,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [374] = 3,
    ACTIONS(94), 1,
      anon_sym_SQUOTE,
    ACTIONS(96), 1,
      anon_sym_EQ_GT,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [385] = 3,
    ACTIONS(72), 1,
      anon_sym_LBRACK,
    STATE(33), 1,
      sym__slots,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [396] = 3,
    ACTIONS(98), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      sym__class_specification,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [407] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [416] = 3,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    STATE(13), 1,
      sym_slot_definition,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [427] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(102), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [436] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [445] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(106), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [454] = 3,
    ACTIONS(15), 1,
      anon_sym_POUNDname,
    STATE(4), 1,
      sym__simple_name_definition,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [465] = 3,
    ACTIONS(15), 1,
      anon_sym_POUNDname,
    STATE(59), 1,
      sym__simple_name_definition,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [476] = 3,
    ACTIONS(108), 1,
      anon_sym_SQUOTE,
    ACTIONS(110), 1,
      anon_sym_EQ_GT,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [487] = 3,
    ACTIONS(98), 1,
      anon_sym_LBRACE,
    STATE(66), 1,
      sym__class_specification,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [498] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(112), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [507] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(114), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [516] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(116), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [525] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(118), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [534] = 3,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    STATE(46), 1,
      sym_slot_definition,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [545] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(120), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [554] = 2,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
    ACTIONS(70), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [563] = 2,
    ACTIONS(122), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [571] = 2,
    ACTIONS(124), 1,
      anon_sym_LBRACK,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [579] = 2,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [587] = 2,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [595] = 2,
    ACTIONS(130), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [603] = 2,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [611] = 2,
    ACTIONS(134), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [619] = 2,
    ACTIONS(136), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [627] = 2,
    ACTIONS(138), 1,
      sym_dashed_name,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [635] = 2,
    ACTIONS(140), 1,
      sym_dashed_name,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [643] = 2,
    ACTIONS(142), 1,
      sym_dashed_name,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [651] = 2,
    ACTIONS(144), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [659] = 2,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [667] = 2,
    ACTIONS(148), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [675] = 2,
    ACTIONS(150), 1,
      anon_sym_Class,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [683] = 2,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [691] = 2,
    ACTIONS(154), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [699] = 2,
    ACTIONS(156), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [707] = 2,
    ACTIONS(158), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [715] = 2,
    ACTIONS(160), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [723] = 2,
    ACTIONS(162), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [731] = 2,
    ACTIONS(164), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [739] = 2,
    ACTIONS(166), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [747] = 2,
    ACTIONS(168), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [755] = 2,
    ACTIONS(170), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [763] = 2,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [771] = 2,
    ACTIONS(174), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [779] = 2,
    ACTIONS(176), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [787] = 2,
    ACTIONS(178), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [795] = 2,
    ACTIONS(180), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [803] = 2,
    ACTIONS(182), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [811] = 2,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [819] = 2,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [827] = 2,
    ACTIONS(188), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [835] = 2,
    ACTIONS(190), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [843] = 2,
    ACTIONS(192), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [851] = 2,
    ACTIONS(194), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
  [859] = 2,
    ACTIONS(196), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_continuation,
      sym_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 115,
  [SMALL_STATE(6)] = 130,
  [SMALL_STATE(7)] = 145,
  [SMALL_STATE(8)] = 156,
  [SMALL_STATE(9)] = 170,
  [SMALL_STATE(10)] = 180,
  [SMALL_STATE(11)] = 194,
  [SMALL_STATE(12)] = 204,
  [SMALL_STATE(13)] = 214,
  [SMALL_STATE(14)] = 228,
  [SMALL_STATE(15)] = 242,
  [SMALL_STATE(16)] = 252,
  [SMALL_STATE(17)] = 266,
  [SMALL_STATE(18)] = 280,
  [SMALL_STATE(19)] = 291,
  [SMALL_STATE(20)] = 300,
  [SMALL_STATE(21)] = 309,
  [SMALL_STATE(22)] = 318,
  [SMALL_STATE(23)] = 327,
  [SMALL_STATE(24)] = 336,
  [SMALL_STATE(25)] = 345,
  [SMALL_STATE(26)] = 354,
  [SMALL_STATE(27)] = 363,
  [SMALL_STATE(28)] = 374,
  [SMALL_STATE(29)] = 385,
  [SMALL_STATE(30)] = 396,
  [SMALL_STATE(31)] = 407,
  [SMALL_STATE(32)] = 416,
  [SMALL_STATE(33)] = 427,
  [SMALL_STATE(34)] = 436,
  [SMALL_STATE(35)] = 445,
  [SMALL_STATE(36)] = 454,
  [SMALL_STATE(37)] = 465,
  [SMALL_STATE(38)] = 476,
  [SMALL_STATE(39)] = 487,
  [SMALL_STATE(40)] = 498,
  [SMALL_STATE(41)] = 507,
  [SMALL_STATE(42)] = 516,
  [SMALL_STATE(43)] = 525,
  [SMALL_STATE(44)] = 534,
  [SMALL_STATE(45)] = 545,
  [SMALL_STATE(46)] = 554,
  [SMALL_STATE(47)] = 563,
  [SMALL_STATE(48)] = 571,
  [SMALL_STATE(49)] = 579,
  [SMALL_STATE(50)] = 587,
  [SMALL_STATE(51)] = 595,
  [SMALL_STATE(52)] = 603,
  [SMALL_STATE(53)] = 611,
  [SMALL_STATE(54)] = 619,
  [SMALL_STATE(55)] = 627,
  [SMALL_STATE(56)] = 635,
  [SMALL_STATE(57)] = 643,
  [SMALL_STATE(58)] = 651,
  [SMALL_STATE(59)] = 659,
  [SMALL_STATE(60)] = 667,
  [SMALL_STATE(61)] = 675,
  [SMALL_STATE(62)] = 683,
  [SMALL_STATE(63)] = 691,
  [SMALL_STATE(64)] = 699,
  [SMALL_STATE(65)] = 707,
  [SMALL_STATE(66)] = 715,
  [SMALL_STATE(67)] = 723,
  [SMALL_STATE(68)] = 731,
  [SMALL_STATE(69)] = 739,
  [SMALL_STATE(70)] = 747,
  [SMALL_STATE(71)] = 755,
  [SMALL_STATE(72)] = 763,
  [SMALL_STATE(73)] = 771,
  [SMALL_STATE(74)] = 779,
  [SMALL_STATE(75)] = 787,
  [SMALL_STATE(76)] = 795,
  [SMALL_STATE(77)] = 803,
  [SMALL_STATE(78)] = 811,
  [SMALL_STATE(79)] = 819,
  [SMALL_STATE(80)] = 827,
  [SMALL_STATE(81)] = 835,
  [SMALL_STATE(82)] = 843,
  [SMALL_STATE(83)] = 851,
  [SMALL_STATE(84)] = 859,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extensions_definition, 2, 0, 2),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extensions_definition, 3, 0, 2),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_extensions_definition_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_extensions_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_name_definition, 5, 0, 19),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_definition, 3, 0, 10),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_definition, 4, 0, 13),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_definition, 5, 0, 18),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__class_specification_repeat1, 2, 0, 17),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__class_specification_repeat1, 2, 0, 17), SHIFT_REPEAT(3),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_definition, 6, 0, 20),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__slots_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__slots_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__slots, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__class_field, 1, 0, 3),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__class_field, 1, 0, 4),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__class_field, 1, 0, 5),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__class_field, 1, 0, 6),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__class_field, 1, 0, 7),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__class_field, 1, 0, 8),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__class_field, 1, 0, 9),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_definition, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__instance_slots, 3, 0, 14),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__class_slots, 3, 0, 15),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__class_specification_repeat1, 2, 0, 1),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__superclass, 5, 0, 21),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__package, 5, 0, 22),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__tag, 5, 0, 23),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__category, 5, 0, 24),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__slots, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 2, 0, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_definition, 4, 0, 12),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__class_specification, 4, 0, 16),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 3, 0, 11),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [182] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__class_specification, 3, 0, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 1, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pharo(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "pharo",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
